"""
build_embedded.py
Generates embedded_data.js containing all minimap images (base64 JPEG)
and all JSON data files inlined as JS variables.
"""
import base64
import json
import os
from io import BytesIO
from PIL import Image

ROOT = os.path.dirname(os.path.abspath(__file__))

# ── Minimap images ──────────────────────────────────────────────────────────
MINIMAP_DIR = os.path.join(ROOT, "minimaps")
MINIMAP_FILES = {
    "AmbroseValley": "AmbroseValley_Minimap.png",
    "GrandRift":     "GrandRift_Minimap.png",
    "Lockdown":      "Lockdown_Minimap.jpg",
}

embedded_minimaps = {}
for map_name, filename in MINIMAP_FILES.items():
    path = os.path.join(MINIMAP_DIR, filename)
    img = Image.open(path).convert("RGB")
    img = img.resize((512, 512), Image.LANCZOS)
    buf = BytesIO()
    img.save(buf, format="JPEG", quality=72)
    b64 = base64.b64encode(buf.getvalue()).decode("ascii")
    embedded_minimaps[map_name] = f"data:image/jpeg;base64,{b64}"
    size_kb = len(buf.getvalue()) / 1024
    print(f"  {map_name}: {size_kb:.1f} KB -> base64 {len(b64)//1024} KB")

# ── JSON data files ─────────────────────────────────────────────────────────
DATA_DIR = os.path.join(ROOT, "data")
embedded_data = {}
for filename in sorted(os.listdir(DATA_DIR)):
    if not filename.endswith(".json"):
        continue
    key = filename[:-5]  # strip .json
    with open(os.path.join(DATA_DIR, filename), encoding="utf-8") as f:
        embedded_data[key] = json.load(f)
    print(f"  {key}: loaded")

# ── Write embedded_data.js ──────────────────────────────────────────────────
out_path = os.path.join(ROOT, "embedded_data.js")
with open(out_path, "w", encoding="utf-8") as out:
    out.write("// Auto-generated by build_embedded.py — do not edit manually\n")
    out.write("// Embed all minimap images as base64 data URIs\n")
    out.write("const EMBEDDED_MINIMAPS = ")
    out.write(json.dumps({k: v for k, v in embedded_minimaps.items()}, separators=(",", ":")))
    out.write(";\n\n")
    out.write("// Embed all match + meta JSON data\n")
    out.write("const EMBEDDED_DATA = ")
    out.write(json.dumps(embedded_data, separators=(",", ":")))
    out.write(";\n")

size_mb = os.path.getsize(out_path) / (1024 * 1024)
print(f"\nWrote embedded_data.js  ({size_mb:.2f} MB)")
print("GitHub 100MB limit: " + ("OK" if size_mb < 100 else "EXCEEDS LIMIT — add to .gitignore"))
